# Generated by Django 4.1.7 on 2023-06-28 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_call_close_at_call_state_alter_call_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='receivers',
        ),
        migrations.AddField(
            model_name='call',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reveiver_caller', to='chat.employee'),
        ),
    ]
