# Generated by Django 4.1.7 on 2023-06-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_remove_messagegroupe_receivers_employeehasgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeegroup',
            name='initial',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
