# Generated by Django 4.1.7 on 2023-07-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
